### ISSUE TITLE
Не работает отправка в эластик из консьюмера логов

### ISSUE THREAD

**Issue by melnikk** [vostok/airlock.consumer#17]

**Comment by trurl123** [comment]
13:54:09.995 WRN [poll-ElasticLogsIndexerEntryPoint@b336d264e9df-airlock@b336d264e9df] PartitionsAssigned: consumerName: airlock@b336d264e9df#consumer-1, memberId: airlock@b336d264e9df-6abc723b-a751-4ba8-996e-c27ce8d54254, topicPartitions: [vostok.dev.contrailsapi.logs [0] @Invalid [-1001]]

**Comment by AndrewKostousov** [comment]
Закрываю этот ишью, поскольку непонятно, что нужно исправить. Feel free to reopen, как говорится.
