### ISSUE TITLE
Ждать пока консьюмеры закончат фетчинг и обработать полученные события в ConsumerGroupHost перед завершением процесса

### ISSUE THREAD

**Issue by trurl123** [vostok/airlock.consumer#20]

**Comment by AndrewKostousov** [comment]
Кажется, ни к чему обрабатывать все зафетченные события. Наоборот, лучше и ConsumerGroupHost переписать в таком ключе - как только получен стоп-сигнал, максимально быстро останавливаем процессоры и выходим. И забиваем на все, что есть во внутренних очередях что у драйвера, что у нас. К просиранию событий это не приводит, поскольку мы не комитим, то что не обработали. А завершить процесс позволяет быстрее. Это важно, поскольку рантайм бесконечно нашего завершения ждать не будет - там 10 сек, что ли докер нам отводит на остановку. И лучше мы сами gracefully остановимся, чем нас прибьют в каком-то непонятном состоянии.

**Comment by AndrewKostousov** [comment]
resolved via PR #23
