### ISSUE TITLE
В консьюмере по отправке в Sentry реализовать поддержку множества проектов

### ISSUE THREAD

**Issue by trurl123** [vostok/airlock.consumer#37]
На каждый проект в Sentry выделяется API-key, который используется в коннекте. Необходимо реализовать маппинг из проекта востока в проект сентри и поддерживать пулл коннектов.

**Comment by trurl123** [comment]
See PR https://github.com/vostok/airlock.consumer/pull/40

**Comment by AndrewKostousov** [comment]
PR #40 merged
