### ISSUE TITLE
Ошибка в логике TracesToEvents

### ISSUE THREAD

**Issue by beevee** [vostok/airlock.consumer#44]
![2017-12-15_21-31-25](https://user-images.githubusercontent.com/1009675/34051381-2d98b01a-e1e0-11e7-962d-d823cf14dac1.png)

**Comment by beevee** [comment]
Получается, что у нас есть метрики, не относящиеся ни к какому коду ответа.

**Comment by beevee** [comment]
У нас с @spaceorc есть гипотеза, что с приложений приходят трассировки с пустым полем "код ответа". Это само по себе отдельный баг, мы его поправим. Но в консьюмере нужно предусмотреть, чтобы трассировки с пустыми полями попадали в какую-то специальную группу (например, empty), а не в корень. И чтобы они считались в any.

**Comment by beevee** [comment]
То же самое хорошо бы предусмотреть для случая пустого поля с хостом, пустого поля с контроллером и т.д. Чтобы структура и длина имени метрики была одинаковой вне зависимости от заполненности полей.

**Comment by spaceorc** [comment]
Кажется, что править надо в коде не агрегатора а в коде TracesToEvents - именно там формирутся события по http-requests трассировкам. Это только там мы знаем структуру события.

**Comment by trurl123** [comment]
Сейчас уже в ветке MergeTraceEvents эта логика перенесена в агрегатор метрик. Иван, может ты посмотришь эту ветку, а то Андрей все занят?

**Comment by trurl123** [comment]
Во время сетевого запроса может приходить не только HttpException, но и WebException, который уже не содержит HTTP-кода ответа, поэтому с точки зрения клиента это вполне допустимая ситуация.

**Comment by trurl123** [comment]
Поправил в мастере, чтобы теги заполнялись и такой ошибки не было. Довольно простые изменения, поэтому не через pull request.
Буду дальше разбираться, почему скидываются такие трейсы.

**Comment by trurl123** [comment]
Пока не получается воспроизводить такую ошибку. Я обнаружил, что иван в Bluetape уже поправил эту проблему.
