### ISSUE TITLE
Баг потери событий из нового топика

### ISSUE THREAD

**Issue by trurl123** [vostok/airlock.consumer#45]
Если события начинают отправляться в топик, которого еще не было, то консьюмеры теряют какое-то количество первых событий.
Происходит потому что по-умолчанию используется offset, равный Ignored (если Stored, то то же самое происходит).
Консьюмер обнаруживает новый топик, подписывается на него и встает в конец очереди.

**Comment by AndrewKostousov** [comment]
Думаю, правильное решение - это в случае, когда сохраненного оффсета нет, отступать на какую-то дельту по времени в прошлое и начинать читать с нее. Такая ситуация случается когда а) создается новый топик и уже запущенный консьюмер его подхватывает, и б) когда запускается новая консьюмер-группа для существующих топиков.
